export const tiendas = [{
		type: 'super mercado',
		name: 'la popular',
		image: 'images/stores/1.jpg',
		ubicacion: 'Av 53, tamares, Urb andres bello',
		map: 'geolocalicación - cordenadas',
		description: 'Ven a comprar en la Popular, los mejores precios.',
	},
	{
		type: 'abastecimiento',
		name: 'Compre con menos eliaser',
		image: 'images/stores/2.jpg',
		ubicacion: 'Carretera 83, la pica pica',
		map: 'geolocalicación - cordenadas',
		description: 'Todo lo que necesitas al mejor precio',
	},
	{
		type: 'tienda',
		name: 'Gran avenida',
		image: 'images/stores/3.jpg',
		ubicacion: 'Centro, plaza bolivar, frente a farmabien',
		map: 'geolocalicación - cordenadas',
		description: 'Con los mejores precios del mercado, ven ya!',
	},
	{
		type: 'farmacia',
		name: 'farmatodo',
		image: 'images/stores/4.jpg',
		ubicacion: 'Av alteriar 7, frente a la policia',
		map: 'geolocalicación - cordenadas',
		description: 'Somo tu lugar ideal para comprar de todo',
	},
	{
		type: 'ferreteria',
		name: 'feinca',
		image: 'images/stores/5.jpg',
		ubicacion: 'Av. san francisco, via auto part',
		map: 'geolocalicación - cordenadas',
		description: 'Buscas herramientas ?, aqui encontraras de todo',
	},
	{
		type: 'panaderia',
		name: 'la pandoro',
		image: 'images/stores/6.jpg',
		ubicacion: 'Centro, calle san morros, via lorenso',
		map: 'geolocalicación - cordenadas',
		description: 'Lo mejor en pan, dulces, y comidas',
	},
	{
		type: 'tienda',
		name: 'gina',
		image: 'images/stores/7.jpg',
		ubicacion: 'Centro, via san jose, frente a la parada',
		map: 'geolocalicación - cordenadas',
		description: 'Todo en ropa, vestidos, calsados, y mas',
	},
	{
		type: 'puesto de comida rapida',
		name: 'morochos burguer',
		image: 'images/stores/8.jpg',
		ubicacion: 'Centro, via san jose, frente a la parada',
		map: 'geolocalicación - cordenadas',
		description: 'Todo en ropa, vestidos, calsados, y mas',
	},
	// ----

	{
		type: 'farmacia2',
		name: 'farmatodo2',
		image: 'images/stores/9.jpg',
		ubicacion: 'Av alteriar 7, frente a la policia',
		map: 'geolocalicación - cordenadas',
		description: 'Somo tu lugar ideal para comprar de todo',
	},
	{
		type: 'ferreteria2',
		name: 'feinca2',
		image: 'images/stores/10.jpg',
		ubicacion: 'Av. san francisco, via auto part',
		map: 'geolocalicación - cordenadas',
		description: 'Buscas herramientas ?, aqui encontraras de todo',
	},
	{
		type: 'tienda2',
		name: 'Gran avenida2',
		image: 'images/stores/11.jpg',
		ubicacion: 'Centro, plaza bolivar, frente a farmabien',
		map: 'geolocalicación - cordenadas',
		description: 'Con los mejores precios del mercado, ven ya!',
	},
	{
		type: 'farmacia2',
		name: 'farmatodo2',
		image: 'images/stores/12.jpg',
		ubicacion: 'Av alteriar 7, frente a la policia',
		map: 'geolocalicación - cordenadas',
		description: 'Somo tu lugar ideal para comprar de todo',
	},
	{
		type: 'ferreteria2',
		name: 'feinca2',
		image: 'images/stores/13.jpg',
		ubicacion: 'Av. san francisco, via auto part',
		map: 'geolocalicación - cordenadas',
		description: 'Buscas herramientas ?, aqui encontraras de todo',
	},
]
